---
name: Create Specification Document

# The workflow is triggered by pull request, push to main, and manual dispatch.
on:
  workflow_dispatch:
    inputs:
      revision_mark:
        description: 'Set revision mark as Draft, Release or Stable:'
        required: true
        type: choice
        options:
          - Development
          - Stable
          - Frozen
          - Ratified
        default: Development
      prerelease:
        description: Tag as a pre-release?
        required: false
        type: boolean
        default: true
      draft:
        description: Create release as a draft?
        required: false
        type: boolean
        default: false
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get next version
        uses: reecetech/version-increment@2024.4.4
        id: version
        with:
          scheme: semver
          increment: patch

      # Pull the latest RISC-V Docs container image
      - name: Pull Container
        run: docker pull riscvintl/riscv-docs-base-container-image:latest

      # Override VERSION and REVMARK for manual workflow dispatch
      - name: Update environment variables
        run: |
          echo "VERSION=v${{ steps.version.outputs.version }}" >> "$GITHUB_ENV"
          echo "REVMARK=${{ github.event.inputs.revision_mark }}" >> "$GITHUB_ENV"
        if: github.event_name == 'workflow_dispatch'

      # Build Files
      - name: Build Files
        id: build_files
        run: make -j$(nproc)

      # Upload the built PDF files as a single artifact
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Artifacts
          path: ${{ github.workspace }}/build/*.pdf
          retention-days: 30

      # Upload the riscv-c-api PDF file
      - name: Upload riscv-c-api.pdf
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
            name: riscv-c-api-${{ env.SHORT_SHA }}.pdf
            path: ${{ github.workspace }}/build/riscv-c-api.pdf
            retention-days: 7

      # Upload the riscv-c-api HTML file
      - name: Upload riscv-c-api.html
        if: steps.build_files.outcome == 'success'
        uses: actions/upload-artifact@v4
        with:
            name: riscv-c-api-${{ env.SHORT_SHA }}.html
            path: ${{ github.workspace }}/build/riscv-c-api.html
            retention-days: 7

      # Create Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/build/*.pdf
          tag_name: v${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          draft: ${{ github.event.inputs.draft }}
          prerelease: ${{ github.event.inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GHTOKEN }}
        if: github.event_name == 'workflow_dispatch'
        # This condition ensures this step only runs for workflow_dispatch events.

      - name: Make GitHub pages directory
        run: |
          mkdir -p dist/snapshot/riscv-c-api
          cp build/*.html dist/snapshot/riscv-c-api/index.html
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist
        if: github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && github.ref == 'refs/heads/main')

  # Deploy HTML to Github pages.
  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    needs: build

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
